# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  # Ideally we'd like to mount the volume on your disk in order to not lose data.
  # But this tiny project is based on my windows OS which docker volume mount is
  # not stable yet, so I decided to comment the line below out.
  # volumes:
  #   - /my/own/datadir:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  redis-cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"